#!/usr/bin/env perl

use strict;

sub check {
  my ( $sha1 ) = @_;
  my $filename = $ENV{'srcdir'} . '/../../alfalfa_test_vectors/' . ${sha1};
  unless ( -e $filename ) {
      print STDERR "$0: $sha1 not found, skipping test.\n";
      exit 77; # automake error code for test skip
  }

  print STDERR "Checking $sha1... ";
  my $decoded_sha1 = (split ' ', `./decode-to-stdout $filename | sha1sum` )[ 0 ];
  if ( $decoded_sha1 ne $sha1 ) {
    print STDERR "$0: decoding mismatch: expected $sha1, got $decoded_sha1\n";
    exit( 1 );
  }
  print STDERR "success.\n";
};

check( 'ff2941dde20090835032c32c0644b6d401610c57' );

print STDERR "$0: all tests passed\n";

exit 0;
