#!/usr/bin/env perl

use strict;
use File::Path 'rmtree';

sub switch_check {
  my ( $switch_num, $source, $target ) = @_;
  my $source_file = '../../alfalfa_test_vectors/' . ${source};
  my $target_file = '../../alfalfa_test_vectors/' . ${target};

  my $randsuffix = sprintf "%08X", rand(0xffffffff);
  my $dirname = "switch-dump$randsuffix";

  system("../frontend/frameify $dirname $source_file $target_file") and die "Failed framify";
  system("../frontend/alfalfa-weave $dirname $switch_num") and die "Failed denseify";
  my $frameify_sha1 = (split ' ', `./videodir-to-stdout $dirname $switch_num | sha1sum`)[ 0 ];

  rmtree [ $dirname ];

  my $correct_sha1 = (split ' ', `./switch-to-stdout $switch_num $source_file $target_file | sha1sum`)[ 0 ];

  if ( $frameify_sha1 ne $correct_sha1 ) {
    print STDERR "$0: switch mismatch: expected $correct_sha1, got $frameify_sha1\n";
    exit ( 1 );
  }
  print STDERR "success.\n";
};

switch_check( 5, 'dbdd07032180b63689fc0475cdfac1ed927cd253',
              '353ee97f6cc145f43be2f67c893ec0347d822cc1' );
print STDERR "$0: all tests passed\n";

exit 0;
