#!/bin/bash

# make sure you add v4l2loopback module by running 'modprobe v4l2loopback' before this

if [ "$#" -ne 2 ]
then
  echo "usage: fake-camera INPUT_VIDEO CAMERA_DEV"
  exit 1
fi

trap "exit" INT TERM
trap "kill 0" EXIT

ffmpeg -re -i $1 -f v4l2 $2
