#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;
use HTTP::Request::Common;

my $username = $ARGV[ 0 ];
my $video = $ARGV[ 1 ];
my $camera_device = $ARGV[ 2 ];
if ( (not defined $username) or (not defined $video) or (not defined $camera_device) ) {
  die "Usage: $0 USERNAME VIDEO_FILE CAMERA_DEVICE\n";
}

my $receiver_pid = fork;

if ( $receiver_pid < 0 ) {
  die qq{$!};
} elsif ( $receiver_pid == 0 ) {
  # child
  exec q{salsify-receiver 9090 1280 720} or die qq{$!};
}

my $fakewebcam_pid = fork;

if ( $fakewebcam_pid < 0 ) {
  die qq{$!};
} elsif ( $fakewebcam_pid == 0 ) {
  #child
  exec qq{ffmpeg -hide_banner -loglevel panic -re -i $video -f v4l2 $camera_device} or die qq{$!};
}

sleep 4;

chomp( my $prefix = qx{dirname `which mm-link`} );
my $tracedir = $prefix . q{/../share/mahimahi/traces};

# run the sender inside a linkshell and a delayshell
my @command = qw{mm-delay 20 mm-link UPLINK DOWNLINK};

# display livegraphs if we seem to be running under X
if ( defined $ENV{ 'DISPLAY' } ) {
  push @command, qw{--meter-uplink --meter-uplink-delay};
}

push @command, qw{--once --uplink-log=/tmp/contest_uplink_log -- sh -c};

push @command, qq{salsify-sender --mode conventional --update-rate 1 -d $camera_device -p YU12 \$MAHIMAHI_BASE 9090 1337};

# for the contest, we will send data over Verizon's downlink
# (datagrump sender's uplink)
die unless $command[ 3 ] eq "UPLINK";
$command[ 3 ] = qq{$tracedir/Verizon-LTE-short.down};

die unless $command[ 4 ] eq "DOWNLINK";
$command[ 4 ] = qq{$tracedir/Verizon-LTE-short.up};

system @command;

# kill the receiver
print "Killing the receiver and the fakewebcam...";
kill 'INT', $receiver_pid;
kill 'INT', $fakewebcam_pid;
print " done.\n";

print "\n";

# analyze performance locally
system q{mm-throughput-graph 500 /tmp/contest_uplink_log > /dev/null}
  and die q{mm-throughput-graph exited with error.};

print "\n";

=pod
# gzip logfile
print q{Uploading data to server...};

my $www = LWP::UserAgent->new();
my $request = POST 'http://cs344g.keithw.org/cgi-bin/6829/upload-data',
  Content_Type => 'multipart/form-data',
  Content => [contents => ['/tmp/contest_uplink_log', $username]];

my $response = $www->request( $request );

print qq{ done.\n\n};

print $response->decoded_content;

print "\n";
=cut
